/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pilasycolas;

/**
 *
 * @author Libni
 */
public class frm_pilascolas extends javax.swing.JFrame {

    /**
     * Creates new form frm_pilascolas
     */
    public frm_pilascolas() {
        initComponents();
    }
    Generador gen = new Generador();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_pila = new javax.swing.JButton();
        btn_cola = new javax.swing.JButton();
        lbl_pila = new javax.swing.JLabel();
        lbl_cola = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pilas Y Colas");

        btn_pila.setBackground(new java.awt.Color(153, 255, 255));
        btn_pila.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_pila.setText("Generar numeros en una Pila");
        btn_pila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilaActionPerformed(evt);
            }
        });

        btn_cola.setBackground(new java.awt.Color(153, 255, 255));
        btn_cola.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_cola.setText("Generar numeros en una Cola");
        btn_cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colaActionPerformed(evt);
            }
        });

        lbl_pila.setBackground(new java.awt.Color(51, 204, 255));
        lbl_pila.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_pila.setForeground(new java.awt.Color(204, 204, 204));
        lbl_pila.setText("Tiempo que se ha tardado el programa en realizar la accion: ");

        lbl_cola.setBackground(new java.awt.Color(51, 204, 255));
        lbl_cola.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_cola.setForeground(new java.awt.Color(204, 204, 204));
        lbl_cola.setText("Tiempo que se ha tardado el programa en realizar la accion: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_pila)
                            .addComponent(btn_pila)
                            .addComponent(btn_cola)
                            .addComponent(lbl_cola))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_pila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_cola)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilaActionPerformed
        // TODO add your handling code here:
        gen.Pila();
        this.lbl_pila.setText("Tiempo que se ha tardado el programa en realizar la accion: "+Double.toString(gen.getTiempo())+" milisegundos");
    }//GEN-LAST:event_btn_pilaActionPerformed

    private void btn_colaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colaActionPerformed
        // TODO add your handling code here:
        gen.Cola();
        this.lbl_cola.setText("Tiempo que se ha tardado el programa en realizar la accion: "+Double.toString(gen.getTiempo())+" milisegundos");
    }//GEN-LAST:event_btn_colaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_pilascolas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_pilascolas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_pilascolas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_pilascolas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_pilascolas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cola;
    private javax.swing.JButton btn_pila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cola;
    private javax.swing.JLabel lbl_pila;
    // End of variables declaration//GEN-END:variables
}
